
package models

// BindingsMinusWebsocketsMinus_0Dot_1Dot_0MinusChannelHeaders represents a BindingsMinusWebsocketsMinus_0Dot_1Dot_0MinusChannelHeaders model.
type BindingsMinusWebsocketsMinus_0Dot_1Dot_0MinusChannelHeaders struct {
  Schema
  Reference
}