
package models

// BindingsMinusSnsMinus_0Dot_1Dot_0MinusChannelStatementPrincipal represents a BindingsMinusSnsMinus_0Dot_1Dot_0MinusChannelStatementPrincipal model.
type BindingsMinusSnsMinus_0Dot_1Dot_0MinusChannelStatementPrincipal struct {
  string
  ModelinaArrType []string
}