
package models

// BindingsMinusMqttMinus_0Dot_2Dot_0MinusServerSessionExpiryInterval represents a BindingsMinusMqttMinus_0Dot_2Dot_0MinusServerSessionExpiryInterval model.
type BindingsMinusMqttMinus_0Dot_2Dot_0MinusServerSessionExpiryInterval struct {
  int
  Schema
  Reference
}