
package models

// BindingsMinusSqsMinus_0Dot_2Dot_0MinusOperationStatementPrincipal represents a BindingsMinusSqsMinus_0Dot_2Dot_0MinusOperationStatementPrincipal model.
type BindingsMinusSqsMinus_0Dot_2Dot_0MinusOperationStatementPrincipal struct {
  string
  ModelinaArrType []string
}