
package models

// BindingsMinusWebsocketsMinus_0Dot_1Dot_0MinusChannelQuery represents a BindingsMinusWebsocketsMinus_0Dot_1Dot_0MinusChannelQuery model.
type BindingsMinusWebsocketsMinus_0Dot_1Dot_0MinusChannelQuery struct {
  Schema
  Reference
}