
package models

// BindingsMinusSolaceMinus_0Dot_4Dot_0MinusOperationDestinationsItem represents a BindingsMinusSolaceMinus_0Dot_4Dot_0MinusOperationDestinationsItem model.
type BindingsMinusSolaceMinus_0Dot_4Dot_0MinusOperationDestinationsItem struct {
  BindingsMinusSolaceMinus_0Dot_4Dot_0MinusOperationDestinationsItemOneOf_0
  BindingsMinusSolaceMinus_0Dot_4Dot_0MinusOperationDestinationsItemOneOf_1
}