
package models

// BindingsMinusMqttMinus_0Dot_2Dot_0MinusMessageCorrelationData represents a BindingsMinusMqttMinus_0Dot_2Dot_0MinusMessageCorrelationData model.
type BindingsMinusMqttMinus_0Dot_2Dot_0MinusMessageCorrelationData struct {
  Schema
  Reference
}