
package models

// BindingsMinusSqsMinus_0Dot_2Dot_0MinusOperationStatementAction represents a BindingsMinusSqsMinus_0Dot_2Dot_0MinusOperationStatementAction model.
type BindingsMinusSqsMinus_0Dot_2Dot_0MinusOperationStatementAction struct {
  string
  ModelinaArrType []string
}