
package models

// BindingsMinusSnsMinus_0Dot_1Dot_0MinusOperationConsumerFilterPolicyAdditionalProperty represents a BindingsMinusSnsMinus_0Dot_1Dot_0MinusOperationConsumerFilterPolicyAdditionalProperty model.
type BindingsMinusSnsMinus_0Dot_1Dot_0MinusOperationConsumerFilterPolicyAdditionalProperty struct {
  ModelinaArrType []string
  string
  ModelinaDictType map[string]interface{}
}