
package models

// BindingsMinusSqsMinus_0Dot_2Dot_0MinusChannelStatementPrincipal represents a BindingsMinusSqsMinus_0Dot_2Dot_0MinusChannelStatementPrincipal model.
type BindingsMinusSqsMinus_0Dot_2Dot_0MinusChannelStatementPrincipal struct {
  string
  ModelinaArrType []string
}