
package models

// BindingsMinusMqttMinus_0Dot_2Dot_0MinusOperationMessageExpiryInterval represents a BindingsMinusMqttMinus_0Dot_2Dot_0MinusOperationMessageExpiryInterval model.
type BindingsMinusMqttMinus_0Dot_2Dot_0MinusOperationMessageExpiryInterval struct {
  int
  Schema
  Reference
}