
package models

// JsonMinusSchemaMinusDraftMinus_07MinusSchemaDependenciesAdditionalProperty represents a JsonMinusSchemaMinusDraftMinus_07MinusSchemaDependenciesAdditionalProperty model.
type JsonMinusSchemaMinusDraftMinus_07MinusSchemaDependenciesAdditionalProperty struct {
  CoreSchemaMetaMinusSchema
  ModelinaArrType []string
}