
package models

// JsonMinusSchemaMinusDraftMinus_07MinusSchemaItems represents a JsonMinusSchemaMinusDraftMinus_07MinusSchemaItems model.
type JsonMinusSchemaMinusDraftMinus_07MinusSchemaItems struct {
  JsonMinusSchemaMinusDraftMinus_07MinusSchema
  ModelinaArrType []JsonMinusSchemaMinusDraftMinus_07MinusSchema
}