
package models
import (  
  "encoding/json"
)
// BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem represents an enum of BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem.
type BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem uint

const (
  BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemCompact BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem = iota
  BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemDelete
)

// Value returns the value of the enum.
func (op BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem) Value() any {
	if op >= BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem(len(BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemValues)) {
		return nil
	}
	return BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemValues[op]
}

var BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemValues = []any{"compact","delete"}
var ValuesToBindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem = map[any]BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem{
  BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemValues[BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemCompact]: BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemCompact,
  BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemValues[BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemDelete]: BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItemDelete,
}

 
          
func (op *BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem) UnmarshalJSON(raw []byte) error {
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return err
	}
	*op = ValuesToBindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem[v]
	return nil
}

func (op BindingsMinusKafkaMinus_0Dot_4Dot_0MinusChannelTopicConfigurationCleanupDotPolicyItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(op.Value())
} 
          