
package models

// JsonMinusSchemaMinusDraftMinus_07MinusSchemaItems represents a JsonMinusSchemaMinusDraftMinus_07MinusSchemaItems model.
type JsonMinusSchemaMinusDraftMinus_07MinusSchemaItems struct {
  CoreSchemaMetaMinusSchema
  ModelinaArrType []CoreSchemaMetaMinusSchema
}