
package models

// JsonMinusSchemaMinusDraftMinus_07MinusSchemaAdditionalItems represents a JsonMinusSchemaMinusDraftMinus_07MinusSchemaAdditionalItems model.
type JsonMinusSchemaMinusDraftMinus_07MinusSchemaAdditionalItems struct {
  bool
  JsonMinusSchemaMinusDraftMinus_07MinusSchema
}