
package models

// JsonMinusSchemaMinusDraftMinus_07MinusSchemaType represents an enum of JsonMinusSchemaMinusDraftMinus_07MinusSchemaType.
type JsonMinusSchemaMinusDraftMinus_07MinusSchemaType uint

const (
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeArray JsonMinusSchemaMinusDraftMinus_07MinusSchemaType = iota
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeBoolean
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeInteger
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeNumber
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeObject
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeString
)

// Value returns the value of the enum.
func (op JsonMinusSchemaMinusDraftMinus_07MinusSchemaType) Value() any {
	if op >= JsonMinusSchemaMinusDraftMinus_07MinusSchemaType(len(JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeValues)) {
		return nil
	}
	return JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeValues[op]
}

var JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeValues = []any{"array","boolean","integer","number","object","string"}
var ValuesToJsonMinusSchemaMinusDraftMinus_07MinusSchemaType = map[any]JsonMinusSchemaMinusDraftMinus_07MinusSchemaType{
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeValues[JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeArray]: JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeArray,
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeValues[JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeBoolean]: JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeBoolean,
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeValues[JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeInteger]: JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeInteger,
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeValues[JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeNumber]: JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeNumber,
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeValues[JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeObject]: JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeObject,
  JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeValues[JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeString]: JsonMinusSchemaMinusDraftMinus_07MinusSchemaTypeString,
}
