
package models

// JsonMinusSchemaMinusDraftMinus_07MinusSchemaExclusiveMinimum represents a JsonMinusSchemaMinusDraftMinus_07MinusSchemaExclusiveMinimum model.
type JsonMinusSchemaMinusDraftMinus_07MinusSchemaExclusiveMinimum struct {
  float64
  bool
}