name: Test and upload coverage on codecov
on:
    push:
        branches:
            - main
    pull_request: 
        types: [opened, synchronize, reopened, ready_for_review]
jobs:
    test_and_coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: setup go 
              uses: actions/setup-go@v4
              with:
                go-version: '1.23'
            - name: install dependencies
              run: go mod tidy
            - name: Run tests and generate coverage report
              run: go test ./... -coverprofile=coverage.txt
            
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{secrets.CODECOV_TOKEN}}
                fail_ci_if_error: true
