
package models

// JsonMinusSchemaMinusDraftMinus_07MinusSchemaAdditionalProperties represents a JsonMinusSchemaMinusDraftMinus_07MinusSchemaAdditionalProperties model.
type JsonMinusSchemaMinusDraftMinus_07MinusSchemaAdditionalProperties struct {
  bool
  JsonMinusSchemaMinusDraftMinus_07MinusSchema
}